language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2/repository

script:
  - ./yang-lsp/gradlew -p yang-lsp build --refresh-dependencies --no-daemon

notifications:
  slack: theia-dev:wZFIkC6bV4WUqsnT6YxzGoMq
