language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2/repository

before_script:
  - git clone https://github.com/TypeFox/xtext-jflex.git
  - mvn -f ./xtext-jflex/jflex-fragment/pom.xml clean install

script:
  - ./yang-lsp/gradlew -p yang-lsp build

notifications:
  slack: theia-dev:wZFIkC6bV4WUqsnT6YxzGoMq